create table if not exists public.blog_comments (
  id bigint generated by default as identity primary key,
  post_slug text not null,
  parent_id bigint references public.blog_comments(id) on delete cascade,
  name text not null,
  email text not null,
  message text not null check (char_length(message) between 1 and 1000),
  is_anonymous boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.blog_comments
  add column if not exists is_hidden boolean not null default false;

alter table public.blog_comments
  add column if not exists hidden_at timestamptz;

create index if not exists blog_comments_post_slug_idx
  on public.blog_comments (post_slug);

create index if not exists blog_comments_parent_id_idx
  on public.blog_comments (parent_id);

alter table public.blog_comments enable row level security;

drop policy if exists "comments_public_select" on public.blog_comments;
create policy "comments_public_select"
  on public.blog_comments
  for select
  to anon, authenticated
  using (is_hidden = false);

drop policy if exists "comments_owner_select_all" on public.blog_comments;
create policy "comments_owner_select_all"
  on public.blog_comments
  for select
  to authenticated
  using ((auth.jwt() ->> 'email') = 'shubhamofficial0910@gmail.com');

drop policy if exists "comments_public_insert" on public.blog_comments;
create policy "comments_public_insert"
  on public.blog_comments
  for insert
  to anon, authenticated
  with check (
    char_length(trim(name)) > 0
    and char_length(trim(email)) > 0
    and char_length(trim(message)) between 1 and 1000
  );

drop policy if exists "comments_public_delete" on public.blog_comments;
drop policy if exists "comments_owner_delete" on public.blog_comments;
create policy "comments_owner_delete"
  on public.blog_comments
  for delete
  to authenticated
  using ((auth.jwt() ->> 'email') = 'shubhamofficial0910@gmail.com');

drop policy if exists "comments_owner_update_hidden" on public.blog_comments;
create policy "comments_owner_update_hidden"
  on public.blog_comments
  for update
  to authenticated
  using ((auth.jwt() ->> 'email') = 'shubhamofficial0910@gmail.com')
  with check ((auth.jwt() ->> 'email') = 'shubhamofficial0910@gmail.com');

create extension if not exists pgcrypto;

create table if not exists public.blog_comment_reactions (
  id bigint generated by default as identity primary key,
  comment_id bigint not null references public.blog_comments(id) on delete cascade,
  voter_hash text not null,
  vote smallint not null check (vote in (-1, 1)),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (comment_id, voter_hash)
);

create index if not exists blog_comment_reactions_comment_id_idx
  on public.blog_comment_reactions (comment_id);

alter table public.blog_comment_reactions enable row level security;

drop policy if exists "comment_reactions_no_direct_select" on public.blog_comment_reactions;
create policy "comment_reactions_no_direct_select"
  on public.blog_comment_reactions
  for select
  to anon, authenticated
  using (false);

drop policy if exists "comment_reactions_no_direct_insert" on public.blog_comment_reactions;
create policy "comment_reactions_no_direct_insert"
  on public.blog_comment_reactions
  for insert
  to anon, authenticated
  with check (false);

drop policy if exists "comment_reactions_no_direct_update" on public.blog_comment_reactions;
create policy "comment_reactions_no_direct_update"
  on public.blog_comment_reactions
  for update
  to anon, authenticated
  using (false)
  with check (false);

drop policy if exists "comment_reactions_no_direct_delete" on public.blog_comment_reactions;
create policy "comment_reactions_no_direct_delete"
  on public.blog_comment_reactions
  for delete
  to anon, authenticated
  using (false);

create or replace function public.comment_voter_hash()
returns text
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  headers jsonb := coalesce(current_setting('request.headers', true), '{}')::jsonb;
  xff text := split_part(coalesce(headers ->> 'x-forwarded-for', ''), ',', 1);
  real_ip text := coalesce(headers ->> 'x-real-ip', '');
  ip text := nullif(trim(coalesce(xff, real_ip, '')), '');
  ua text := coalesce(headers ->> 'user-agent', '');
  uid text := coalesce(auth.uid()::text, '');
  seed text;
begin
  seed := uid || '|' || coalesce(ip, '') || '|' || ua || '|portfolio-comments-v1';
  return encode(extensions.digest(seed, 'sha256'::text), 'hex');
end;
$$;

grant execute on function public.comment_voter_hash() to anon, authenticated;

create or replace function public.vote_comment(p_comment_id bigint, p_vote smallint)
returns smallint
language plpgsql
security definer
set search_path = public
as $$
declare
  h text;
  existing_vote smallint;
begin
  if p_vote not in (-1, 1) then
    raise exception 'p_vote must be -1 or 1';
  end if;

  if not exists (
    select 1
    from public.blog_comments c
    where c.id = p_comment_id
      and c.is_hidden = false
  ) then
    raise exception 'Comment not found';
  end if;

  h := public.comment_voter_hash();

  select r.vote
  into existing_vote
  from public.blog_comment_reactions r
  where r.comment_id = p_comment_id
    and r.voter_hash = h;

  if existing_vote = p_vote then
    delete from public.blog_comment_reactions
    where comment_id = p_comment_id
      and voter_hash = h;
    return 0;
  end if;

  insert into public.blog_comment_reactions(comment_id, voter_hash, vote, created_at, updated_at)
  values (p_comment_id, h, p_vote, now(), now())
  on conflict (comment_id, voter_hash)
  do update set
    vote = excluded.vote,
    updated_at = now();

  return p_vote;
end;
$$;

grant execute on function public.vote_comment(bigint, smallint) to anon, authenticated;

drop function if exists public.get_comment_reaction_stats(text);

create or replace function public.get_comment_reaction_stats(p_post_slug text)
returns table (
  comment_id bigint,
  likes integer,
  dislikes integer,
  my_vote smallint
)
language sql
security definer
set search_path = public
as $$
  with me as (
    select public.comment_voter_hash() as voter_hash
  )
  select
    c.id as comment_id,
    coalesce(sum(case when r.vote = 1 then 1 else 0 end), 0)::int as likes,
    coalesce(sum(case when r.vote = -1 then 1 else 0 end), 0)::int as dislikes,
    coalesce(max(case when r.voter_hash = (select voter_hash from me) then r.vote end), 0)::smallint as my_vote
  from public.blog_comments c
  left join public.blog_comment_reactions r on r.comment_id = c.id
  where c.post_slug = p_post_slug
    and c.is_hidden = false
  group by c.id;
$$;

grant execute on function public.get_comment_reaction_stats(text) to anon, authenticated;
