create table if not exists public.visitor_events (
  id bigint generated by default as identity primary key,
  ip_address text,
  user_agent text,
  ip_hash text not null,
  ua_hash text not null,
  page_slug text,
  device_type text,
  browser_name text,
  os_name text,
  referrer text,
  created_at timestamptz not null default now()
);

alter table public.visitor_events
  add column if not exists ip_address text;

alter table public.visitor_events
  add column if not exists user_agent text;

create index if not exists visitor_events_created_at_idx
  on public.visitor_events (created_at desc);

create index if not exists visitor_events_page_slug_idx
  on public.visitor_events (page_slug);

create index if not exists visitor_events_device_type_idx
  on public.visitor_events (device_type);

create or replace function public.cleanup_visitor_events()
returns void
language sql
security definer
as $$
  delete from public.visitor_events
  where created_at < now() - interval '30 days';
$$;

create or replace function public.visitor_ip_hash()
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  headers jsonb;
  xff text;
  real_ip text;
  ip text;
begin
  begin
    headers := coalesce(current_setting('request.headers', true)::jsonb, '{}'::jsonb);
  exception when others then
    headers := '{}'::jsonb;
  end;
  
  xff := split_part(coalesce(headers ->> 'x-forwarded-for', ''), ',', 1);
  real_ip := coalesce(headers ->> 'x-real-ip', '');
  ip := nullif(trim(coalesce(xff, real_ip, '')), '');

  return coalesce(ip, 'unknown-ip');
end;
$$;

grant execute on function public.visitor_ip_hash() to anon, authenticated;

create or replace function public.visitor_ua_hash()
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  headers jsonb;
  ua text;
begin
  begin
    headers := coalesce(current_setting('request.headers', true)::jsonb, '{}'::jsonb);
  exception when others then
    headers := '{}'::jsonb;
  end;

  ua := nullif(trim(coalesce(headers ->> 'user-agent', '')), '');
  return coalesce(ua, 'unknown-ua');
end;
$$;

grant execute on function public.visitor_ua_hash() to anon, authenticated;

create or replace function public.log_visitor(
  p_page_slug text,
  p_device_type text,
  p_browser_name text,
  p_os_name text,
  p_referrer text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.visitor_events (
    ip_address,
    user_agent,
    ip_hash,
    ua_hash,
    page_slug,
    device_type,
    browser_name,
    os_name,
    referrer,
    created_at
  ) values (
    public.visitor_ip_hash(),
    public.visitor_ua_hash(),
    public.visitor_ip_hash(),
    public.visitor_ua_hash(),
    p_page_slug,
    p_device_type,
    p_browser_name,
    p_os_name,
    p_referrer,
    now()
  );
end;
$$;

grant execute on function public.log_visitor(text, text, text, text, text) to anon, authenticated;

create or replace function public.get_visitor_stats(p_days_back integer default 7)
returns table (
  total_visits bigint,
  unique_visitors bigint,
  top_pages text,
  top_devices text,
  top_browsers text,
  top_os text
)
language sql
security definer
set search_path = public
as $$
  select
    count(*)::bigint as total_visits,
    count(distinct (
      coalesce(nullif(ip_address, ''), ip_hash) || '|' || coalesce(nullif(user_agent, ''), ua_hash)
    ))::bigint as unique_visitors,
    string_agg(distinct page_slug, ', ' order by page_slug) as top_pages,
    string_agg(distinct device_type, ', ' order by device_type) as top_devices,
    string_agg(distinct browser_name, ', ' order by browser_name) as top_browsers,
    string_agg(distinct os_name, ', ' order by os_name) as top_os
  from public.visitor_events
  where created_at > now() - (p_days_back || ' days')::interval;
$$;

grant execute on function public.get_visitor_stats(integer) to anon, authenticated;

alter table public.visitor_events enable row level security;

drop policy if exists "visitor_events_no_direct_select" on public.visitor_events;
create policy "visitor_events_no_direct_select"
  on public.visitor_events
  for select
  to anon, authenticated
  using (false);

drop policy if exists "visitor_events_no_direct_insert" on public.visitor_events;
create policy "visitor_events_no_direct_insert"
  on public.visitor_events
  for insert
  to anon, authenticated
  with check (false);
